name: Build WinRing0 DLL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-winring0:
    runs-on: windows-2022  # 固定版本避免 windows-latest 迁移问题

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build WinRing0 DLL (x64 Release)
        run: msbuild WinRing0Dll\WinRing0Dll2017.vcxproj /p:Configuration=Release /p:Platform=x64

      - name: Upload DLL and headers
        uses: actions/upload-artifact@v4
        with:
          name: winring0-dll
          path: |
            WinRing0Dll\OlsApi.h
            WinRing0Dll\WinRing0x64.dll
