name: Build WinRing0

on:
  workflow_dispatch:   # 手动触发
  push:                # 或者每次 push 时触发
    branches:
      - master

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup Visual Studio Developer Command Prompt
        uses: egor-tensin/vs-shell@v2

      - name: Build WinRing0 (x64 Release)
        run: msbuild WinRing0.sln /p:Configuration=Release /p:Platform=x64

      - name: Build WinRing0 (x86 Release)
        run: msbuild WinRing0.sln /p:Configuration=Release /p:Platform=Win32

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: winring0-build
          path: |
            **/Release/*.dll
            **/Release/*.lib
            **/Release/*.sys
            **/OlsApi.h
